name: Build
on: [push, pull_request]

jobs:

  build_sdist:
    name: Build Source Distribution (sdist)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz


  linux:
    name: ${{ matrix.config.os }} Python ${{ matrix.config.py_version }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
        config:
          - { os: ubuntu-latest, py_version: 3.8 }
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.py_version }}

      - name: Install Python libraries
        run: |
          pip install --user -r requirements.txt

      - name: Install CGAL
        run: |
          sudo apt-get -qq install libcgal-dev

      - name: Configure
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPYBIND11_PYTHON_VERSION=${{ matrix.config.py_version }} ..

      - name: Build
        run: |
          cd build
          cmake --build .
          make install

      - name: Test
        run: |
          cd build
          make check-installed
