name: Build
on: [push, pull_request]

jobs:
  linux:
    name: ${{ matrix.config.os }} Python ${{ matrix.config.py_version }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        build_type: ["Debug", "RelWithDebInfo", "Release"]
        config:
          - { os: ubuntu-latest, py_version: 3.8 }
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt-get -qq install python${{ matrix.config.py_version }}

      - name: Install CGAL
        run: |
          sudo apt-get -qq install libcgal-dev

      - name: Configure
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPYBIND11_PYTHON_VERSION=${{ matrix.config.py_version }} ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Test
        run: |
          cd build
          make check
